{% set version = "0.2.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-docxtools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/docxtools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/docxtools/docxtools_{{ version }}.tar.gz
  sha256: d8e91bf37c3f09d4f12bbd0a670f86b7f589dc7fef196b2b4e989d1e84c74837

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-lubridate
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tidyr
  run:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-lubridate
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tidyr

test:
  commands:
    - $R -e "library('docxtools')"           # [not win]
    - "\"%R%\" -e \"library('docxtools')\""  # [win]

about:
  home: https://graphdr.github.io/docxtools
  license: MIT
  summary: A set of helper functions for using R Markdown to create documents in docx format, especially documents for use in a classroom or workshop setting.
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r

# Package: docxtools
# Title: Tools for R Markdown to Docx Documents
# Version: 0.2.1
# Language: en-US
# Authors@R: c( person("Richard", "Layton", email = "graphdoctor@gmail.com", role = c("aut", "cre")) )
# Description: A set of helper functions for using R Markdown to create documents in docx format, especially documents for use in a classroom or workshop setting.
# Depends: R (>= 3.1.2)
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: TRUE
# RoxygenNote: 6.1.1
# Imports: dplyr, ggplot2, lubridate, purrr, rlang, stringr, tidyr
# Suggests: covr, knitr, rmarkdown, rprojroot, testthat
# VignetteBuilder: knitr
# URL: https://graphdr.github.io/docxtools
# BugReports: https://github.com/graphdr/docxtools/issues
# NeedsCompilation: no
# Packaged: 2019-02-09 18:25:19 UTC; layton
# Author: Richard Layton [aut, cre]
# Maintainer: Richard Layton <graphdoctor@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-02-09 18:43:13 UTC
