{% set version = "0.2.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-docxtools
  version: {{ version|replace("-", "_") }}

source:
  fn: docxtools_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/docxtools_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/docxtools/docxtools_{{ version }}.tar.gz
  sha256: 5917d91ba1ffda3385c26e4eaa174d493f0653e80208754c3cd7de0b490be757

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-pander
    - r-stringr
    - r-tidyr
    - r-lubridate
  run:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-pander
    - r-stringr
    - r-tidyr
    - r-lubridate

test:
  commands:
    - $R -e "library('docxtools')"  # [not win]
    - "\"%R%\" -e \"library('docxtools')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=docxtools
  license: MIT
  summary: A set of helper functions for using R Markdown to create documents in docx format,
    especially documents for use in a classroom or workshop setting.
  license_family: MIT

extra:
  recipe-maintainers:
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
