# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "L7Bdbh9b4CuahCfvepkAS06UEzQR/zAsDNLMVD2BXs6Y9bnlGzMBfZYkJJ+WE1XKIYp85Rkh3chnfpuTgQzvoHr0wJcyScbrbnLXxm4zwALAPD1AHad/3v+4irRCi8AG/wiE4BMUak2684zy8c5BW8ql3vJM2rBIfbPzpXwzAusAGYje6g/l2t1AHpl16LwHSf0MBXqYKMB5qUN2CgBxWbEpCQBl0wccNzzCDlsqE5EHaQoexdQvOP2zHcX1SiRNejer5pZukCxW6Y9DxpAPTyqe/tum3uZnRavBpCt1P5Qldair3hAW9UWnjrkI4FOgtekIlvPcambFiGekC8yp9/wQbWFFVPRS5gEz7dV+G5vpCVrNjMk2vNhPjUQbOwALGZVCKa/Dad+nMvRQ0szxBFUU3flMCNpqf7ZWf/C8i7X5HHH9rWSrLX1XigpBh742ZUBAMHwV9UJ46mI9UtnOLHGjN3nh0rWXKKFhR67bYqmo7Zl6DneRVv5sdsi72FsR/ZMsp4n24fXGQdfb+BGTge7Tnk79izlNdgaUgH+JNZ0o2bhX6v5nIh9HLxk2IKA5MbIA7LCbS6DpwEyK18wfAAoRkdmQW7+4mzkcvGxlHM6W18pWKJAFTudGWReUSvS3O29XHypctiHDnLDzD8LBTqAsziZGG/acRqO9iKVXxkY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
