travis:
  secure:
    BINSTAR_TOKEN: L7Bdbh9b4CuahCfvepkAS06UEzQR/zAsDNLMVD2BXs6Y9bnlGzMBfZYkJJ+WE1XKIYp85Rkh3chnfpuTgQzvoHr0wJcyScbrbnLXxm4zwALAPD1AHad/3v+4irRCi8AG/wiE4BMUak2684zy8c5BW8ql3vJM2rBIfbPzpXwzAusAGYje6g/l2t1AHpl16LwHSf0MBXqYKMB5qUN2CgBxWbEpCQBl0wccNzzCDlsqE5EHaQoexdQvOP2zHcX1SiRNejer5pZukCxW6Y9DxpAPTyqe/tum3uZnRavBpCt1P5Qldair3hAW9UWnjrkI4FOgtekIlvPcambFiGekC8yp9/wQbWFFVPRS5gEz7dV+G5vpCVrNjMk2vNhPjUQbOwALGZVCKa/Dad+nMvRQ0szxBFUU3flMCNpqf7ZWf/C8i7X5HHH9rWSrLX1XigpBh742ZUBAMHwV9UJ46mI9UtnOLHGjN3nh0rWXKKFhR67bYqmo7Zl6DneRVv5sdsi72FsR/ZMsp4n24fXGQdfb+BGTge7Tnk79izlNdgaUgH+JNZ0o2bhX6v5nIh9HLxk2IKA5MbIA7LCbS6DpwEyK18wfAAoRkdmQW7+4mzkcvGxlHM6W18pWKJAFTudGWReUSvS3O29XHypctiHDnLDzD8LBTqAsziZGG/acRqO9iKVXxkY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
