travis:
  secure:
    BINSTAR_TOKEN: L84tw022lnbv1YUQ/S9nBXWA7oIY4SWNjHIvgtu51822yUFvgjjMmCBbWtNXeBBIYNMcDfagzHM11ba1t6+2SeAcD8tqCWcuHkGUGUWChsaK1JSJ0/JsFUVMrtoxQSClSLMfp6/JOINXdoFmOWTMnE/UR3LX6qaehy56o1bpvuo70SFhoXQGuSNMJFpQevj0Ar/0/MyCI4EoIycya+YENl9jXSfrxz45/iPVVPmcvF5o8H6ptCaEaeAr873vEN8zM9tjT8LevINJ+qggB4JfFCbESJ1TIc8IWG7KOWeo3OQrw2jcwipOwWsDrPW568q7QKeFpiS2gcwhSn93sxph6Ekbl1+uXgDJO3fUQT0dFvvQ3S7zF2Yj29X6sEZUXs3z+ruuOOd+At+/L19RuXzbOqboNaDwopmaLlbfTMYDmU88ZxVVa4LyO1Ddcw/Z74zGx/ZYq0hhz4D0i99zidU8fz48LX1T/2imbNET/nswXebdCKXXgYO5gOsI13HWSvd0ObGOEwEJqNpL3rsWXsqO4MjCe6/mzzPaU5SN1JTcRh0XSvUmQEVY6kCd2GNpWogEXwR8BMCviBLi/MFgbcXbC8bbxKkELEsADYBQ9HsLTi7sFVXwRqSxXxOjl2nbrFtXMrOy0KbOZUeWFWR2MiozoWBzVUejXNJYEHCMMSLq2Ec=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
