travis:
  secure:
    BINSTAR_TOKEN: a4v7+P+qy2p0u3Y3TQVEvMYVPPt/5JMIiLJoUKjUgeEQh7klgX1ySK9JO1wkK/mKjdxGDVY+Isj8rbWPMcnay54lA94rfMpz6RRAY+ZZZOdwzggEGE0DZVOJvHdvKc2x1+s+7TzVcES+1OpxqyFN/kAGGExMBpE6cPwpUv0peWHcHTpzz0ALuEevYpzqEtBQM6mLckUQ1K50Zbq7P1tKvQXZY05FHo7yINdvp6kzY/uUFOLcFu0Z0WupwXXiryTZvBZCgS1dXYQXQkgqcpb/sr/yvrHSOvhyuBvqlFYOYHsgiHjeCf687mUlorRa/O06oYsJ26zulfJuP6yJoPTD4OhGq19yXY7LcIHDj8Ne+9VhLw8Q5T+tGsent7L9b6vAQPwBBDhfMhwLud/JamnRTa7dvExJBTjWaTT9hL78/Fp38YvDWch7rRml1qGY6/kgY01P+Plr4opFnivZUMeI/+0Pl+BgkaIe970Vziv8LWX9RH81MbSgVOs0hsQj7JSvCzRKxWjdNaorf+2Wzw5HRRNboAhNJuXoMC5KMujZTrAUFnWFBiapzAdI9fvo5xsPWO1O4L1XXQ3Xm9GNWVlDPMr2LpNoQeVxbCxOcf13rawPiAUfVT8cvJ7/+PT33wf0zB32F86cmUxfHu8l+e68CrOp2NWAx20dE2vRqCgw66c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
